{% set name = "AnyQt" %}
{% set version = "0.2.0" %}
{% set sha256 = "4b9228b918a26df2fdcc61f135db548ad3c3036e5bc7e67ba8147e0b6683763b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1

  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools

  run:
    - python >={{ python_min }}
    - pyqt

test:
  requires:
    - python {{ python_min }}
  imports:
    - AnyQt.QtCore
    - AnyQt.QtGui
    - AnyQt.QtWidgets
    - AnyQt.QtNetwork
    - AnyQt.QtSvg

about:
  home: https://github.com/ales-erjavec/anyqt/
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  summary: PyQt4/PyQt5 compatibility layer.
  doc_url: http://anyqt.readthedocs.io/en/0.0.7/
  dev_url: https//github.com/ales-erjavec/anyqt

extra:
  recipe-maintainers:
    - ales-erjavec
    - astaric
