{% set name = "AnyQt" %}
{% set version = "0.0.8" %}
{% set sha256 = "7f1f71ce744e940fb49da0a302d972a9561c0844ab67df77091d631c6f2687b6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2

  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pyqt 5.6.*

test:
  imports:
    - AnyQt.QtCore
    - AnyQt.QtGui
    - AnyQt.QtWidgets
    - AnyQt.QtNetwork
    - AnyQt.QtSvg

about:
  home: https://github.com/ales-erjavec/anyqt/
  license: GPL-3.0
  license_family: GPL3
  summary: PyQt4/PyQt5 compatibility layer.
  doc_url: http://anyqt.readthedocs.io/en/0.0.7/
  dev_url: https//github.com/ales-erjavec/anyqt

extra:
  recipe-maintainers:
     - ales-erjavec
     - astaric
