{% set name = "AnyQt" %}
{% set version = "0.1.0" %}
{% set sha256 = "aa261a28c3da6e7d9cee16fab209343b272b9f7ab39ad42ae02dc1687834c402" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0

  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python >=3.6
    - pyqt

test:
  imports:
    - AnyQt.QtCore
    - AnyQt.QtGui
    - AnyQt.QtWidgets
    - AnyQt.QtNetwork
    - AnyQt.QtSvg

about:
  home: https://github.com/ales-erjavec/anyqt/
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  summary: PyQt4/PyQt5 compatibility layer.
  doc_url: http://anyqt.readthedocs.io/en/0.0.7/
  dev_url: https//github.com/ales-erjavec/anyqt

extra:
  recipe-maintainers:
    - ales-erjavec
    - astaric
