{% set name = "AnyQt" %}
{% set version = "0.0.10" %}
{% set sha256 = "d62238f2bdf3dc8343072da3192e7953bc9a48b1e6d012091cfaba956b697036" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0

  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - pyqt

test:
  imports:
    - AnyQt.QtCore
    - AnyQt.QtGui
    - AnyQt.QtWidgets
    - AnyQt.QtNetwork
    - AnyQt.QtSvg

about:
  home: https://github.com/ales-erjavec/anyqt/
  license: GPL-3.0
  license_family: GPL3
  summary: PyQt4/PyQt5 compatibility layer.
  doc_url: http://anyqt.readthedocs.io/en/0.0.7/
  dev_url: https//github.com/ales-erjavec/anyqt

extra:
  recipe-maintainers:
     - ales-erjavec
     - astaric
