{% set name = "AnyQt" %}
{% set version = "0.0.12" %}
{% set sha256 = "07712ec4eb249cc450e6a0abf3841be0bde1850d00824ca1f0f4fa6c5919fa15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0

  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python >=3.6
    - pyqt

test:
  imports:
    - AnyQt.QtCore
    - AnyQt.QtGui
    - AnyQt.QtWidgets
    - AnyQt.QtNetwork
    - AnyQt.QtSvg

about:
  home: https://github.com/ales-erjavec/anyqt/
  license: GPL-3.0
  license_file: LICENSE.txt
  license_family: GPL3
  summary: PyQt4/PyQt5 compatibility layer.
  doc_url: http://anyqt.readthedocs.io/en/0.0.7/
  dev_url: https//github.com/ales-erjavec/anyqt

extra:
  recipe-maintainers:
    - ales-erjavec
    - astaric
