travis:
  secure:
    BINSTAR_TOKEN: r+kfPwlGeddNQG/6Xthmu2c5I/2LfBvmelT1DuHzAhxCpJnc0Ba28CuOqQkrxWglxlzZazv6eZXK53LjEusxyA77BJTo/8wXwOPgO35F9hgllSv1se2b+SLjsO9qaM15W20TrloTcsoaJxnsraqK8uZ9whPt3AvYgPBRWR9Jf28R3y9LH4joIVP7kvGX2mra3BtLOhkhwAUNF9yvZ7521gh7435WGas4Te2DrZg4V0nmoJoc3m+YTWbbICce5zvktm13rozfKMon/pKxy3qPAJonLOwz9c19CHQLK1lEq/qOfsoi6931NlzFa9YXG55tFetRGKSCHVJw2t6WqnpIc4eVD7yBQSKYHBI+k924KItKMUzKl+ncybS/1ghWqVjmORSLslPzAlL90fy1sTFNuKqARrgMpLYTMjwWARSQljIrpI+iSS6GuIUtglvQcGDwXtSl8/angEDAdk0Uw8iuPX/VKwgM3JFs+cUWM1izYtXxtq9JdpWYYE3m8z0LSARtgPIlRxn60wvfoPgyC7sL2VPswdLQ8vWuhJqXdkb5sl/Nt2PjPZ8wN5r0ZSls9OYWsh04prP12fAJ7+RaFdTMF337jlu6WOTr2MKKVaXvGQBSCVbliqXoJxMz3XZIX7tDBHuebVkQFGM8Y3YoOMqw7SV1uGXT8TMzNgXMqWiP65o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
